//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loc_statedivision
    {
        public loc_statedivision()
        {
            this.loc_township = new HashSet<loc_township>();
            this.loc_stock_location = new HashSet<loc_stock_location>();
        }
    
        public int statedivision_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string statedivision_name { get; set; }
    
        public virtual loc_country loc_country { get; set; }
        public virtual ICollection<loc_township> loc_township { get; set; }
        public virtual ICollection<loc_stock_location> loc_stock_location { get; set; }
    }
}
