//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loc_township
    {
        public loc_township()
        {
            this.customers = new HashSet<customer>();
            this.loc_stock_location = new HashSet<loc_stock_location>();
            this.suppliers = new HashSet<supplier>();
        }
    
        public int township_id { get; set; }
        public Nullable<int> statedivision_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string township_name { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
        public virtual loc_country loc_country { get; set; }
        public virtual loc_statedivision loc_statedivision { get; set; }
        public virtual ICollection<loc_stock_location> loc_stock_location { get; set; }
        public virtual ICollection<supplier> suppliers { get; set; }
    }
}
