//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class posEntities : DbContext
    {
        public posEntities()
            : base("name=posEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_role> admin_role { get; set; }
        public virtual DbSet<admin_user> admin_user { get; set; }
        public virtual DbSet<avail_stock_products> avail_stock_products { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_payment_left> customer_payment_left { get; set; }
        public virtual DbSet<important_sql> important_sql { get; set; }
        public virtual DbSet<loc_country> loc_country { get; set; }
        public virtual DbSet<loc_statedivision> loc_statedivision { get; set; }
        public virtual DbSet<loc_stock_location> loc_stock_location { get; set; }
        public virtual DbSet<loc_township> loc_township { get; set; }
        public virtual DbSet<stock_in> stock_in { get; set; }
        public virtual DbSet<stock_in_products> stock_in_products { get; set; }
        public virtual DbSet<stock_out> stock_out { get; set; }
        public virtual DbSet<stock_out_products> stock_out_products { get; set; }
        public virtual DbSet<subcategory> subcategories { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supplier_payment_left> supplier_payment_left { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<total_daily_transition> total_daily_transition { get; set; }
    }
}
