//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_out
    {
        public stock_out()
        {
            this.stock_out_products = new HashSet<stock_out_products>();
        }
    
        public int stock_out_id { get; set; }
        public Nullable<System.DateTime> stock_out_time { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> customer_payment { get; set; }
        public Nullable<int> qty_of_producttypes { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<int> customer_payment_left_id { get; set; }
        public Nullable<byte> sent_or_unsent { get; set; }
        public string stock_out_type { get; set; }
        public Nullable<decimal> transport_cost { get; set; }
        public Nullable<decimal> left_amount { get; set; }
        public Nullable<byte> paid_or_unpaid { get; set; }
        public Nullable<decimal> cu_profit { get; set; }
        public Nullable<decimal> temp_profit { get; set; }
        public Nullable<decimal> return_amt { get; set; }
        public Nullable<decimal> real_total_profit { get; set; }
        public Nullable<decimal> get_total_profit { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<int> daily_transition_id { get; set; }
        public Nullable<int> stock_location_id { get; set; }
        public int admin_user_id { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual customer customer { get; set; }
        public virtual total_daily_transition total_daily_transition { get; set; }
        public virtual ICollection<stock_out_products> stock_out_products { get; set; }
    }
}
