//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_in
    {
        public stock_in()
        {
            this.stock_in_products = new HashSet<stock_in_products>();
        }
    
        public int stock_in_id { get; set; }
        public Nullable<System.DateTime> stock_in_time { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<decimal> supplier_payment { get; set; }
        public Nullable<int> qty_of_producttypes { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<int> supplier_payment_left_id { get; set; }
        public Nullable<byte> move_to_stock { get; set; }
        public Nullable<decimal> left_amount { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<decimal> return_amt { get; set; }
        public Nullable<int> daily_transition_id { get; set; }
        public Nullable<int> admin_user_id { get; set; }
        public Nullable<int> stock_location_id { get; set; }
        public Nullable<decimal> transport_cost { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> tax_percent { get; set; }
        public Nullable<decimal> overall_discount { get; set; }
        public Nullable<decimal> overall_discount_percent { get; set; }
        public byte stock_status { get; set; }
        public Nullable<decimal> other_fees { get; set; }
    
        public virtual admin_user admin_user { get; set; }
        public virtual ICollection<stock_in_products> stock_in_products { get; set; }
        public virtual total_daily_transition total_daily_transition { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual supplier_payment_left supplier_payment_left { get; set; }
        public virtual loc_stock_location loc_stock_location { get; set; }
    }
}
