//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avail_stock_products
    {
        public avail_stock_products()
        {
            this.stock_in_products = new HashSet<stock_in_products>();
            this.stock_out_products = new HashSet<stock_out_products>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> category_id { get; set; }
        public int subcategory_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> current_price { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual category category { get; set; }
        public virtual subcategory subcategory { get; set; }
        public virtual ICollection<stock_in_products> stock_in_products { get; set; }
        public virtual ICollection<stock_out_products> stock_out_products { get; set; }
    }
}
