//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.avail_stock_products = new HashSet<avail_stock_products>();
            this.subcategories = new HashSet<subcategory>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string category_description { get; set; }
    
        public virtual ICollection<avail_stock_products> avail_stock_products { get; set; }
        public virtual ICollection<subcategory> subcategories { get; set; }
    }
}
