//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customer_payment_left = new HashSet<customer_payment_left>();
            this.stock_out_products = new HashSet<stock_out_products>();
            this.stock_out = new HashSet<stock_out>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string address { get; set; }
        public string ph1 { get; set; }
        public string ph2 { get; set; }
        public string ph3 { get; set; }
        public string email { get; set; }
        public Nullable<int> township_id { get; set; }
    
        public virtual ICollection<customer_payment_left> customer_payment_left { get; set; }
        public virtual loc_township loc_township { get; set; }
        public virtual ICollection<stock_out_products> stock_out_products { get; set; }
        public virtual ICollection<stock_out> stock_out { get; set; }
    }
}
