//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loc_stock_location
    {
        public loc_stock_location()
        {
            this.admin_user = new HashSet<admin_user>();
            this.stock_in_products = new HashSet<stock_in_products>();
            this.total_daily_transition = new HashSet<total_daily_transition>();
            this.stock_in = new HashSet<stock_in>();
        }
    
        public int stock_location_id { get; set; }
        public string stock_location_name { get; set; }
        public Nullable<int> township_id { get; set; }
        public string address { get; set; }
        public Nullable<int> statedivision_id { get; set; }
        public Nullable<int> country_id { get; set; }
    
        public virtual ICollection<admin_user> admin_user { get; set; }
        public virtual loc_country loc_country { get; set; }
        public virtual loc_statedivision loc_statedivision { get; set; }
        public virtual loc_township loc_township { get; set; }
        public virtual ICollection<stock_in_products> stock_in_products { get; set; }
        public virtual ICollection<total_daily_transition> total_daily_transition { get; set; }
        public virtual ICollection<stock_in> stock_in { get; set; }
    }
}
