//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_in_products
    {
        public int stock_in_products_id { get; set; }
        public Nullable<int> stock_in_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> product_buy_pric { get; set; }
        public Nullable<decimal> product_sell_default_price { get; set; }
        public Nullable<int> product_qty { get; set; }
        public Nullable<byte> stock_status { get; set; }
        public Nullable<decimal> additional_cost { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> stock_location_id { get; set; }
        public Nullable<System.DateTime> stock_in_time { get; set; }
    
        public virtual avail_stock_products avail_stock_products { get; set; }
        public virtual loc_stock_location loc_stock_location { get; set; }
        public virtual stock_in stock_in { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
