//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_out_products
    {
        public int stock_out_products_id { get; set; }
        public Nullable<int> stock_out_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> profit { get; set; }
        public Nullable<int> product_qty { get; set; }
        public Nullable<byte> sent_or_unsent { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> stock_out_time { get; set; }
    
        public virtual avail_stock_products avail_stock_products { get; set; }
        public virtual customer customer { get; set; }
        public virtual stock_out stock_out { get; set; }
    }
}
