//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        public subcategory()
        {
            this.avail_stock_products = new HashSet<avail_stock_products>();
        }
    
        public int subcategory_id { get; set; }
        public string subcategory_name { get; set; }
        public string subcategory_description { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual ICollection<avail_stock_products> avail_stock_products { get; set; }
        public virtual category category { get; set; }
    }
}
