//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.stock_in = new HashSet<stock_in>();
            this.stock_in_products = new HashSet<stock_in_products>();
            this.supplier_payment_left = new HashSet<supplier_payment_left>();
        }
    
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string address { get; set; }
        public string ph1 { get; set; }
        public string ph2 { get; set; }
        public string ph3 { get; set; }
        public string email { get; set; }
        public Nullable<int> township_id { get; set; }
    
        public virtual loc_township loc_township { get; set; }
        public virtual ICollection<stock_in> stock_in { get; set; }
        public virtual ICollection<stock_in_products> stock_in_products { get; set; }
        public virtual ICollection<supplier_payment_left> supplier_payment_left { get; set; }
    }
}
